import { tokens } from "../theme/tokens";

export const theme = {
  colors: {
    bg: tokens.colors.background,
    bgSecondary: tokens.colors.backgroundSecondary,
    surface: tokens.colors.card,
    surfaceElevated: tokens.colors.cardElevated,
    surfaceHover: "#212128",
    border: tokens.colors.border,
    borderStrong: tokens.colors.borderStrong,
    text: tokens.colors.textPrimary,
    textMuted: tokens.colors.textSecondary,
    textSubtle: "rgba(255,255,255,0.35)",
    accent: tokens.colors.accentBlue,
    accentHover: "#5ea3ff",
    accentWarm: tokens.colors.accentOrange,
    accentPink: "#ff2d55",
    accentPurple: "#b164ff",
    success: tokens.colors.success,
    warning: "#ff9500",
    danger: tokens.colors.danger,
  },
  radius: {
    xs: 8,
    sm: tokens.radius.sm,
    md: tokens.radius.md,
    lg: tokens.radius.lg,
    xl: tokens.radius.xl,
    pill: tokens.radius.pill,
  },
  spacing: {
    xs: tokens.spacing.xs,
    sm: tokens.spacing.sm,
    md: tokens.spacing.md,
    lg: tokens.spacing.lg,
    xl: tokens.spacing.xl,
    xxl: tokens.spacing.xxl,
  },
  typography: tokens.typography,
  shadow: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 10,
    },
    xl: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.4,
      shadowRadius: 28,
      elevation: 14,
    },
  },
};
