import { colors } from "../theme/colors";
import { spacing } from "../theme/spacing";
import { typography } from "../theme/typography";

export const theme = {
  colors: {
    bg: colors.background,
    bgSecondary: colors.background,
    surface: colors.surface,
    surfaceAlt: colors.surfaceAlt,
    surfaceElevated: colors.surfaceAlt,
    surfaceHover: "#212128",
    border: colors.border,
    borderStrong: colors.border,
    text: colors.text,
    textMuted: colors.textMuted,
    textSubtle: "rgba(255,255,255,0.35)",
    accent: colors.accent,
    accentSoft: colors.accentSoft,
    accentHover: "#5ea3ff",
    accentWarm: colors.accent,
    accentPink: "#ff2d55",
    accentPurple: "#b164ff",
    success: colors.success,
    warning: "#ff9500",
    danger: colors.danger,
  },
  radius: {
    xs: 8,
    sm: 12,
    md: 18,
    lg: 20,
    xl: 22,
    pill: 999,
  },
  spacing: {
    xs: spacing.xxs,
    sm: spacing.xs,
    md: spacing.sm,
    lg: spacing.md,
    xl: spacing.lg,
    xxl: 28,
  },
  typography,
  shadow: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 10,
    },
    xl: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.4,
      shadowRadius: 28,
      elevation: 14,
    },
  },
};
