import { Deadline, Goal, LibraryItem, Project } from "./types";

const now = new Date();
const addDays = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const goalsMock: Goal[] = [
  {
    id: "goal-1",
    title: "Chapitre 4 - Fiches",
    subject: "Droit",
    durationMin: 45,
    priority: "high",
    status: "todo",
    dueAt: addDays(1),
    projectId: "project-s2",
    createdAt: now.toISOString(),
  },
  {
    id: "goal-2",
    title: "10 QCM SQL",
    subject: "Informatique",
    durationMin: 25,
    priority: "med",
    status: "doing",
    dueAt: addDays(0),
    projectId: "project-s2",
    createdAt: now.toISOString(),
  },
  {
    id: "goal-3",
    title: "Resume IA - réseaux",
    subject: "IA",
    durationMin: 30,
    priority: "low",
    status: "todo",
    dueAt: addDays(3),
    createdAt: now.toISOString(),
  },
  {
    id: "goal-4",
    title: "Relire cours de procédure",
    subject: "Droit",
    durationMin: 60,
    priority: "high",
    status: "done",
    dueAt: addDays(-1),
    projectId: "project-droit",
    createdAt: now.toISOString(),
  },
  {
    id: "goal-5",
    title: "Fiche microéconomie",
    subject: "Commerce",
    durationMin: 25,
    priority: "med",
    status: "todo",
    dueAt: addDays(6),
    createdAt: now.toISOString(),
  },
];

export const deadlinesMock: Deadline[] = [
  {
    id: "deadline-1",
    title: "Partiel Droit civil",
    subject: "Droit",
    date: addDays(3),
    type: "exam",
    importance: "high",
  },
  {
    id: "deadline-2",
    title: "Rendu projet mobile",
    subject: "Informatique",
    date: addDays(7),
    type: "assignment",
    importance: "high",
    notes: "Version APK + rapport",
  },
  {
    id: "deadline-3",
    title: "Contrôle marketing",
    subject: "Commerce",
    date: addDays(10),
    type: "exam",
    importance: "med",
  },
  {
    id: "deadline-4",
    title: "Oral IA",
    subject: "IA",
    date: addDays(14),
    type: "other",
    importance: "med",
  },
];

export const projectsMock: Project[] = [
  {
    id: "project-s2",
    name: "Partiels S2",
    description: "Plan global de revision pour les partiels de fin de semestre.",
    subjectTags: ["Droit", "Informatique"],
    goalIds: ["goal-1", "goal-2"],
    deadlineIds: ["deadline-1", "deadline-2"],
    libraryItemIds: ["lib-1", "lib-2"],
    progress: 52,
  },
  {
    id: "project-droit",
    name: "Oral Droit public",
    description: "Argumentaire + fiches de jurisprudence.",
    subjectTags: ["Droit"],
    goalIds: ["goal-4"],
    deadlineIds: ["deadline-1"],
    libraryItemIds: ["lib-3"],
    progress: 76,
  },
];

export const libraryItemsMock: LibraryItem[] = [
  {
    id: "lib-1",
    type: "project",
    title: "Révision Droit - S2",
    subtitle: "Projet • 12 ressources",
    subject: "Droit",
    createdAt: addDays(-1),
    updatedAt: addDays(0),
    isPinned: true,
    projectId: "project-s2",
  },
  {
    id: "lib-2",
    type: "flashcards",
    title: "Flashcards SQL joins",
    subtitle: "Flashcards • 45 cartes",
    subject: "Informatique",
    createdAt: addDays(-2),
    updatedAt: addDays(-1),
    projectId: "project-s2",
  },
  {
    id: "lib-3",
    type: "pdf",
    title: "Institutions européennes",
    subtitle: "PDF • 18 pages",
    subject: "Droit",
    createdAt: addDays(-3),
    updatedAt: addDays(-2),
    projectId: "project-droit",
  },
  {
    id: "lib-4",
    type: "summary",
    title: "Résumé institutions européennes",
    subtitle: "Résumé IA • 6 min",
    subject: "Droit",
    createdAt: addDays(-4),
    updatedAt: addDays(-3),
  },
  {
    id: "lib-5",
    type: "quiz",
    title: "Quiz IA réseaux neuronaux",
    subtitle: "Quiz • 12 questions",
    subject: "IA",
    createdAt: addDays(-5),
    updatedAt: addDays(-4),
  },
  {
    id: "lib-6",
    type: "folder",
    title: "Ressources Marketing",
    subtitle: "Dossier • 9 éléments",
    subject: "Commerce",
    createdAt: addDays(-6),
    updatedAt: addDays(-3),
    isLocked: true,
  },
  {
    id: "lib-7",
    type: "note",
    title: "Notes marketing digital",
    subtitle: "Note • 1200 mots",
    subject: "Commerce",
    createdAt: addDays(-7),
    updatedAt: addDays(-6),
  },
  {
    id: "lib-8",
    type: "pdf",
    title: "Méthodologie dissertation",
    subtitle: "PDF • 10 pages",
    subject: "Prépa",
    createdAt: addDays(-8),
    updatedAt: addDays(-7),
  },
  {
    id: "lib-9",
    type: "group",
    title: "Groupe Révisions partiels",
    subtitle: "Groupe • 24 membres",
    subject: "Multimatière",
    createdAt: addDays(-2),
    updatedAt: addDays(-1),
  },
];
